language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_508de1ee5737_key -iv $encrypted_508de1ee5737_iv
  -in client-secret-ipeirotis-gc.json.enc -out client-secret-ipeirotis-gc.json -d
install:
- pip3 install -U jupyter
- pip3 install -U nbformat
- pip3 install -r requirements.txt
script:
- python3 upload_to_google_storage.py
