language: python
python:
- '3.6'
before_install:
- sudo apt-get update
- sudo apt-get install -y python3-pip
- sudo pip3 install -U pip
- suto apt-get install -y curl
- sudo apt-get install -y sqlite3
- sudo apt-get install -y libmysqlclient-dev
- openssl aes-256-cbc -K $encrypted_823613407ecf_key -iv $encrypted_823613407ecf_iv
  -in client-secret-ipeirotis-gc.json.enc -out client-secret-ipeirotis-gc.json -d
install:
- pip3 install -U jupyter
- pip3 install -U nbformat
- pip3 install -r requirements.txt
env:
  global:
    secure: CnbfsWb4KaeEItUeqOs41oj+WTRhE5o5JsLXWiBY9r+KthAK6dTp3FvAdL8CGeCKnaNI5XvruZ9O360N4PvRqhWsj5Q3N4eARMchfDBt6lZ2sAU7edi6BzD2ZwOXr/yxbRpv3qodvfPLEoA/yHarjtfrfwroaQZSgVyRHKGnK2EruqHpVM4Zle3VXzgQpa7Dn25oGCBboYByrunN/jhk3T3miqCrKEoAKanfmteAGQD4pTRwTqhbVie+1xodAUKW4WwlPyDx4EpF6vifspQv1zE83biuqY/vdYZpZWT1b20xLfNUBW92JPbHWCn4+L+QvXi5ZLAktIz7HRulwhy5chKRPmOzQzKgAFela9fhMitpmgKldpdPJdPqOq4bwLOQQ9SWDzeo2OK3pwkRZlRLsuP7iCRDzY4P2VasRRWrmEu5PZc4axs9vYNcfQPkp7/kGjj8AKgYsFGxngOaXfmPLe7EU6VRE1jJe78fhUarpRE5zFykxYXqlcEGpI24Cdi+EI3Pxw95aez8lcJhEMo0KqMwcXqZ6icp7mntWhlYEqel0XuYDF6+8Dpsm+/FU85OiY6BifY89ulMn8Dw7QpanABMkJfgSXLHLAxE5MKLHTocZva9oS6rYWFdq4zaG2Ou/oCO+zL2Jl2XTJdB44DPBzgdehgpASGNqnde3XoJPNA=
script:
- python3 test_notebook.py notebooks/NYPD.ipynb
- mv notebooks/nypd.db data/
- python3 upload_to_google_storage.py
